### ISSUE TITLE
Integrating LightningCache with ETag support for browser caching support?

### ISSUE THREAD

**Issue by richardprice** [creamdog/Nancy.LightningCache#5]
Hey,

How difficult do you think it would be to integrate ETag support (response setting and request checking) to leverage the caching power of LC to handle content 304 Not Modified situations, which you are already determining?

Would this even fall under the scope of the project if I were to do a PR?

Cheers
Richard

**Comment by jchannon** [comment]
I'd be interested in seeing that merged
